# Generated by Django 4.0.4 on 2022-05-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telesettings',
            options={'verbose_name': 'Настройку', 'verbose_name_plural': 'Настройки '},
        ),
    ]
